[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = 'test'
solc_version = '0.8.13'
allow_paths = ["../../node_modules"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config